### ISSUE TITLE
Engineering checklist issues:

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/OpenScale#10]
(1) The design version number is still v04 - This should be v10 if we go to REDS or v05 id we do another proto round. Ether way, the version number needs to change in order to reflect changes from v04.

(2) Need an extra CAP-00810 in the BOM. Currently the design has 9 0.1uf caps and the BOM only reflects 8 of the 9.

(3) I think if the "Serial Ou"t header is to be used as a general serial out, then we should adjust the header so that another micro (pro mini, oplelog, etc.) could be connected directly to the OpenScale with female and male headers without the use of jumper wires. Right now the header is set to mate with an FTDI, which is all good, but it seems redundant given the board has an on-board FTDI chip and a USB connector. I think it would be more intuitive to order the pins similarly to the FTDI's for easy connection to another micro based device. If I am completely off base as to the function of this header please disregard the above.

(4) I know that C14 is directly in the way of the "Serial Out" label being centered, but it would be nice to have that label centered on the header. Maybe smaller font could make this doable. If the font size is already at it's minimum for the need of the design then disregard.

(5) Looks like the trace connecting to the TMP on pin 3 is entering the pad at an angle. It would be nice to have that trace enter the pad at the toe like the rest.

(6) Top copper polygon gets chopped at the corners of the board. I think it would be nice to mimic the bottom copper polygon in nature (same dimension border).

**Comment by ericorosel** [comment]
Mary just reminded me that the Openlog has the same serial header arrangement as the FTDI, which makes point (3) not an issue at all. Please disregard point (3), and my apologies for the confusion.

**Comment by ADataDate** [comment]
Hey Eric,

Pushing changes now. Sorry if this has been frustrating for you. Glad I
have my revision quota done for the year.


(1) The design version number is still v04 - This should be v10 if we go to
REDS or v05 id we do another proto round. Ether way, the version number
needs to change in order to reflect changes from v04. - Changed to v10. The
only changes are adding a cap, connecting the FET to 3.3V which is how it
should be (and when i cut traces and added jumper to exposed trace it
worked perfectly), rounded corners, silk. I don't see how these changes
would affect the performance or intended use of this product. I'd rather
get a product out. However, if you feel it should go for another round of
protos I will take that into consideration as you have more experience with
these types of things here at Sparkfun.

(2) Need an extra CAP-00810 in the BOM. Currently the design has 9 0.1uf
caps and the BOM only reflects 8 of the 9. - Added part in Sparkle

(3) I think if the "Serial Ou"t header is to be used as a general serial
out, then we should adjust the header so that another micro (pro mini,
oplelog, etc.) could be connected directly to the OpenScale with female and
male headers without the use of jumper wires. Right now the header is set
to mate with an FTDI, which is all good, but it seems redundant given the
board has an on-board FTDI chip and a USB connector. I think it would be
more intuitive to order the pins similarly to the FTDI's for easy
connection to another micro based device. If I am completely off base as to
the function of this header please disregard the above. - Discussed, we
agree to keep it the way it is

(4) I know that C14 is directly in the way of the "Serial Out" label being
centered, but it would be nice to have that label centered on the header.
Maybe smaller font could make this doable. If the font size is already at
it's minimum for the need of the design then disregard. - Changed size &
Centered.

(5) Looks like the trace connecting to the TMP on pin 3 is entering the pad
at an angle. It would be nice to have that trace enter the pad at the toe
like the rest. - Done, good catch

(6) Top copper polygon gets chopped at the corners of the board. I think it
would be nice to mimic the bottom copper polygon in nature (same dimension
border). - Done


Mary

**Comment by ADataDate** [comment]
https://github.com/sparkfun/OpenScale/tree/v04
