### ISSUE TITLE
Commercial product?

### ISSUE THREAD

**Issue by zoltan-fedor** [sparkfun/OpenScale#6]
Hi,
I know that the readme says that this project is in prototyping phase, but is it expected at any time that this board becomes commercially available, for example via Sparkfun?

Thanks

**Comment by ToniCorinne** [comment]
I believe @nseidle is still planning on taking the prototypes and putting them through to Production, but I'm not 100% sure on that timeline.

**Comment by zoltan-fedor** [comment]
Thanks @ToniCorinne !

@nseidle , are you still planning on taking this prototype through production? If yes, do you happen to have any timelines?
Thanks

**Comment by nseidle** [comment]
Yep! We have protos but there's many steps left. I'm not sure of the timeline but I will guestimate 3-4 months.

@zoltan-fedor - Your interest level helps move the project along. Would you buy the board if it was available? What are you planning on using it for?

**Comment by zoltan-fedor** [comment]
Yes, depending on the price I would buy at least one (potentially many more - I might have additional projects around the same topic). My current interest is rebuilding a bee hive scale with OpenScale board. Last year I did it by building a board myself, but would be easier to use a pre-built board.

**Comment by ToniCorinne** [comment]
We are working on getting this on the storefront! Closing out the issue, but keep an eye out for the product on the Friday New Product Post.

**Comment by jgpender** [comment]
Can I ask about the status of the OpenScale load sensor board? I am also working on a beehive scale that uploads data to phant, hopefully powered for 2-3 months with a couple AA batteries (C cells are plan B). I've bought all the components from Sparkfun - four SEN-10245 load cells, load sensor combinator BOB-13281, HX711 load cell amp, ESP8266 Dev Thing, and a 3.3 step up breakout NCP1402 to keep the supply voltage very constant. Everything works but I am getting huge temperature drift. A temperature change of a few degrees produces a change in the weight reading equivalent to about 10-20 pounds. Realistic temperature swing of 30 degrees are a nightmare. I added a one-wire temperature sensor to the 8266 in the hopes that I could compensate for the drift in software but I can't get the noise level down to the +/- 1 pound I'd hoped for. Does anyone know if the OpenScale breakout will help with the temperature problem? I don't need to deploy my scale until about June so I still have time to work on this before it's too late for this season. Thanks very much, John.

**Comment by zoltan-fedor** [comment]
I have just finished building mine, but I didn't use the OpenScale board, but built mine.
I believe the big difference that I did not build the scale, but using one already built : http://www.amazon.com/TREE-Measurements-Large-Shipping-Scale/dp/B008M8FND6?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00
Expensive, but reliable, no creep. Left some wait on it for 3 weeks and there wasn't even a 0.1 lb creep.

Also I am using a Particle Electron, so it communicates via the 2G network. Plus it has two batteries, a Lipo and a normal USB battery bank and it charges itself from the UBS battery bank whenever needed, so you can swap the battery bank out whenever you want.

**Comment by jgpender** [comment]
Hiya Zoltan-

How does that work? Do you strip off the display and then tap into the weight reading somehow? I’m assuming this scale works so well either because it uses better load sensors than the Sparkfun set or because it’s somehow built in the temperature compensation. What sort of temperature swing do you get?

Part of what motivated my project was keeping the cost low. I have friends around here with 50-60 hives so $80 just for the scale would break the budget into a million pieces.

Thanks very much,
John

**Comment by zoltan-fedor** [comment]
Hi John,
Yes, this is my second generation bee-scale, last year I built one too - that was with a low-end scale and I had all kind of problems with the reliability of the scale (although no major temperature swings). Currently I am not seeing any temperature swings and this is a high-end scale, so I would be surprised to see any.
Yes, I just stripped off the display and connected the HX711 load cell amp and did the calibration and that's it. I was testing the whole setup in the last 2 weeks - working pretty well.
I really like the Electron, although I must say there were quite a few gotchas when I had to bug the guys at Particle to find solutions to problems of the Electron, specially around sleep modes, low power stages, keeping 2G connection alive, etc.

Zoltan

ps.: Yes, $80 is pretty expensive, but me being a beekeper myself - I would never put a scale under each hive, no point in that, at least not for what I use it. I usually put a scale under a single hive or maybe two - as it is used as an indicator of nectar flow, not the health of the individual hive, so that way it worth the investment for a whole yard.
But yes, for generation 3 of my scale, I will probably do some research to find a cheaper version of the scale - one which is still good enough (no creep, no temperature swings, measures up to 200lb, etc), but cheaper

**Comment by jgpender** [comment]
Hi Zoltan-

I only have the one hive so the expense of the scale is not a big deal, especially when compared to all the aggravation I’ve had. I tried using the Particle Photon but it froze up a couple times so I thought I’d try the ESP8266 board, partly because of the lower price. Talk about “gotchas.” What a pain that board was. I went ahead and used GND, pin 5, pin 0, and pin 4 to connect to the load cell amp and wasted all kinds of time trying to figure out why it didn’t work. Finally realized you’re supposed to connect pin 0 to ground when you want to reset the bootloader so pin 0 doesn’t sleep when you sleep the board.



Shot myself in the foot a second time when I hooked the one-wire temperature sensor to pins 12 and 16. Sleep mode requires a jumper on the blue oval below and I forgot that XPD was the same as pin 16 so, again, the board wouldn’t sleep.


Personally, I’m most comfortable with the Arduino Yun board because I’ve been using command line Unix for 35 years. Scripting, scp, blah blah blah like falling off a log. Spendy board, though, and no sleep mode.

None of my friends would put a scale under every hive either. Usually they set up maybe a half dozen in some field, then another batch in some other location, etc., so they’d only want a scale under one hive per set. Even so, I heard a lot of whining last fall when we talked about the price, even in the $30 range. It was smart of you to start with an industrial-grade solution then work down to something cheap. Starting cheap has cost me all kinds of time.

John

**Comment by zoltan-fedor** [comment]
Hi John,
I am doing a lot of linux too for a few years now, so last year I actually built the whole thing on a Raspberry, but I had a challenge managing its power needs, so now I went for the Particle Electron. I am operating it in the middle of the woods (literally, we take the hives to a black lotus forest), where there is no power source, wifi or anything else (but the woods). :-)

For now I am pretty happy with the Particle Electron. I can run it for about 4-5 days from the included 2000mAh battery making a measurement and sending it to my server in every 15 mins and I can add an any-size external USB power bank and it charges itself from it when the 2000mAh runs low (using a relay switching the USB cabel, because power banks turn themselves off after low power use - when the 2000mAh is full).
I can get a 10000mAh USB power bank fairly cheap ($10), so with that the setup can run for about 24 days in total.
Going any higher would require adding a solar panel (which I did for some other projects) or decreasing measuring frequency to save power.

All-in-all, I am happy with the choice of going industrial-grade with the scale for now and then working down when (if) I plan to produce multiple of these scales.

If somebody wants multiple of these devices, then probably a networked setup would be cheaper than standalone unit:
- connecting them to one central unit via Bluetooth, so you don't need the expensive Particle Electron under each
or
- only sticking a scale under each and then connecting the wires together into a single unit able to call multiple scales, so then you only need a single compute unit, but you need cabling in between the hives

Zoltan

**Comment by jgpender** [comment]
Hi Zoltan-

I’m using 15-minute intervals too, and should get 45-60 days out of a couple AA batteries (~4000mAh) broadcasting to wifi. Logging to an SD card is another way to save power, with data downloads 2-3 times a month with a smart phone and bluetooth during a site visit, but now you have to buy the wifi shield and card. The hive is in my yard and close enough to the house to use the wifi so I prefer a steady data feed. My daughter lobbied hard for a little solar panel, but I decided to just try and keep the energy requirements low. Around here the honey flow lies in a window of about a month depending on weather, so if the batteries last 45 days I win.

John

**Comment by zoltan-fedor** [comment]
Makes sense, different requirements.
For us the black lotus honey flow last only about 7 days and then we need to move the hives to a different forest to catch the black lotus bloom again, so being able to chart in realtime that how much they bring in is very important to determine when to go to move them - but the battery doesn't need to last for month, just 2 weeks tops.
So again, different requirements.

**Comment by jgpender** [comment]
Hi Zoltan-
Having taken apart the nice scale, do you happen to know what it is about the components and/or configuration that allows it to work so well? If I understand you correctly, you used the Photon board and the HX711 board to connect to the scale, which means you used the scale’s load cells - pre-wired in a bridge configuration - and little else. If it’s simply a matter of using better load cells, perhaps Sparkfun could start selling some that work better.

John

**Comment by zoltan-fedor** [comment]
Hi John,
Actually I did not take the nice scale apart, I just took the console apart to see which cable is which and then cut the cable and rewired it to the HX711 board. I actually never looked inside the scale, because it seemed it is glued together and did not want to take it apart. But the same scale has a picture in this article http://makezine.com/projects/bees-sensors-monitor-hive-health/ by the OpenScale guys.
This is where I got the idea to use this scale. They were writing there that they have tried many different scales and all had major creep issues and so they settled with this.
Zoltan

**Comment by ADataDate** [comment]
Hi John,

I'm currently working on the OpenScale board which has the TMP102 sensor
built in so you'll be able to get 2 independent temp readings for your
calibrations. This board is almost ready but will most likely go through
another round of protos for extra testing. I'd be more than happy to send
you a prototype as well, seems like you have been at this for a while. In
fac,t I can send you one in it's current form if you'd like (I'm only
updating silk and moving pins around).  This board, which was originally
designed by Nathan Seidle, comes packed with an Atmega328p, HX711, TMP102,
and load cell combinator in case you are using load sensors instead of a
load cell. It also has a place to hook up a one-wire temp sensor like the
DS18B20.

As far as the problems you are experiencing:
Have you looked into scale creep at all? Sometimes it is not just the
temperature working against you. If you can not tare the scale every so
often (like every 5 minutes in most cases) the scale will fluctuate. Other
factors that can influence your readings are environmental (wind,
vibration), moisture (this will reduce the capacitance on your cables),
pressure differentials, etc. You'll also want to look at the accuracy of
the load cells you are using. And sometimes it is a matter of taking a few
thousand readings and correlating them somehow to get an average you can
work with.

While you are continuing your project please contact me if you need
anything. I'd love to see your set up and help out in any way I can.

Thanks!
Mary

**Comment by jgpender** [comment]
Hi Mary-
Wow, thanks very much for all of this! I would love to try out your proto board, and it sounds plenty far enough along in the design phase for my little project.

Scale creep is indeed my problem. I understand that bathroom scales get around all this by taring immediately before the measurement, and that this simply isn't an option for this outdoor system. I have just discovered something about the load cells I've been using. I would've sworn up until 20 minutes ago that I bought the load cells from Sparkfun, but I pawed through old eReceipts and discovered I'd bought 2 sets of really cheap ($8 per set of 4) load cells off Amazon way back in September when I first started fiddling with this project. Both Zoltan and Nathan (in his MakeZine article) say "don't use cheap load cells" and that is exactly what I did. I feel pretty stupid now, but I've done way stupider stuff than that, believe me. Are Sparkfun's load cells "good enough" or should I buy a nice scale like Zoltan did?

No doubt there are many contributions to the drift I'm observing but temperature is a big factor. I have a sloppy sort of graph of some of my data (below). The first half is outdoors so you see the temperature swing from below freezing to something more balmy each day. There's a few days with low weight load and a few with 40 pounds. You can see the reading shift with the extra weight but the temperature is having a bigger effect on the readings than the weight. I brought it all indoors where the temperature is more stable, but it's warm enough now for windows to be open so the temperature's less steady in here than it was a couple months ago. Still, the mirror correlation between the scale numbers and the temperature are pretty clear, so I'll never get to +/- 1 pound unless ambient temperature is stirred into the soup.

Again, thanks very much for your help on this, Mary.
John


![untitled](https://cloud.githubusercontent.com/assets/11760559/14903837/6c9a0734-0d50-11e6-87ad-c8fd248370f4.jpg)

**Comment by ADataDate** [comment]
You might also want to look into noise that might be on your lines. Another
cool thing about openscale is that Nate added an inductor on the digital
input so some of that noise is immediately filtered. The Inoor weight
actually looks pretty good compared to the outdoor but I can see why would
be frustrated if you are trying to the readings into +/- 1% tolerance.

I would order new load cells. The problem with buying a scale is that you
will get load sensors instead of cells and you would have to configure them
into a whetstone bridge to get it working properly. Do you know the max
weight of what you are trying weigh? We have this Load Cell (data sheet
below as well). It has a pretty good temperature range, creep is +/-0.03%
every 3 minutes.
https://www.sparkfun.com/products/13329
https://cdn.sparkfun.com/datasheets/Sensors/ForceFlex/TAL220M4M5Update.pdf

There are certainly better load cells out there for different applications.
I would check out Honeywell, I usually stop there first for more robust
mechanical projects.

To start compensating the system I would look at one varying factor at a
time. This is how I would get my comp coefficients:
For Creep:
Take a known weight and put in on the scale for as long as the data sheet
says before it needs to tare (in the load cell above its every 3 minutes).
Measure the difference in the measured weight against the known weight. Do
this several times and increase the amount of time with each test.
Eventually you should get a curve which you could probably linearize if you
wanted to keep things a little more simple. The slope of the linear curve
would be your creep coefficient. Yo'll probably need to update this value
often as the creep will change with time.

For Temp:
Do basically the same thing in as much of a controlled environment as you
can. Get ambient readings first then take it outside to get the crazy
stuff. when taking it outside try to shield your setup from as much other
environmental forces as possible. It would be great to characterize the
curve based on you controlling the temperature & humidity/pressure, Since
that isn't totally possible this curve fitting may take some time. Once I
have a coefficient I can test I would set a known weight on the scale in
known temps with an idea of the error might be and adjust the coefficient
statically. You may need to update this value often.

For environmental factors:
Can you dig posts down into the ground, basically create a foundation for
your setup? then it is more likely your setup will not be as susceptible to
vibration. Can you create a housing around the electronics and the
object(s) you are weighing? This will help with wind forces. Though it
would be interesting to see a map of readings with weather data laid over
to see possible correlations. I'd use nice and thick cables, plenty of
electrical tape. Moisture is bad news for transmission.

I'd like to see your data again when you have it set up with OpenScale and
new load cells.

Send me an email at mary.west@sparkfun.com and I'll get you a prototype
loaded the the first sketch ready to go by this afternoon.

Thanks for sharing your progress!

**Comment by abohnsac** [comment]
I'm new to all of this but wondering if anyone has any new information on using the openscale board with their hive sensors. It seems like this should make it more simple and that this has progressed since the release of the board. I'm planning on using it with the raspberry pi 3 to broadcast data. Any guidance or advice is appreciated.
